"""1

Revision ID: 422b5d84d87d
Revises: 
Create Date: 2020-06-05 21:12:00.279288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422b5d84d87d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('contact', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('req', sa.Integer(), nullable=False),
    sa.Column('document_image', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('cur_time', sa.DateTime(), nullable=True),
    sa.Column('accept_time', sa.DateTime(), nullable=True),
    sa.Column('complete_time', sa.DateTime(), nullable=True),
    sa.Column('ngo_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement')
    op.drop_table('ngo')
    # ### end Alembic commands ###
